version: "3.8"

services:
  db:
    image: postgres:17
    container_name: ticketresolve-db
    environment:
      POSTGRES_DB: ticketresolve_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - springnet
    ports:
      - "5432:5432"

  ticketresolve:
    build: .
    container_name: ticketresolve-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ticketresolve_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - springnet

volumes:
  db_data:

networks:
  springnet:
    driver: bridge